version: '3.8'

services:
  postgres:
    container_name: monorepo_postgres
    image: postgres:16
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${DATABASE_PORT}:5432
    networks:
      - database

  mongo:
    container_name: monorepo_mongo
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - mongo_data:/data/db
    ports:
      - ${MONGODB_PORT}:27017
    networks:
      - database

  redis:
    image: redis:latest
    container_name: monorepo_redis
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis_data:/data/spark

volumes:
  postgres_data:
  mongo_data:
  redis_data:

networks:
  database:
